### ISSUE TITLE
HDWallet.from_path() in v3

### ISSUE THREAD

**Issue by mcbarinov** [talonlab/python-hdwallet#105]
There was the wallet.from_path(path="m/44'/1'/0'/0/0") method in v2 version. 
As I understand, from v3 version there is only wallet.from_derivation() method. Is there any way create a derivation parameter from a string like path="m/44'/1'/0'/0/0"?

Thanks!

**Comment by meherett** [comment]
```hdwallet.from_path(path=...)``` is removed you need to use  ```hdwallet.from_derivation()``` then pass derivation

```python
from hdwallet.derivations import CustomDerivation

...

hdwallet.from_derivation(
    derivation=CustomDerivation(
        path="m/44'/1'/0'/0/0"
    )
)

# or

derivation = CustomDerivation()
derivation.from_path(path="m/44'/1'/0'/0/0")
hdwallet.from_derivation(derivation=derivation)


```

Refer
https://github.com/talonlab/python-hdwallet/blob/master/examples/BIPs/from_xpublic_key.py
https://hdwallet.readthedocs.io/en/v3.0.1/derivations.html#hdwallet.derivations.custom.CustomDerivation
