### ISSUE TITLE
Constantly getting TypeError: type 'HDS' is not subscriptable

### ISSUE THREAD

**Issue by pbies** [talonlab/python-hdwallet#107]
HDWallet version 3.1.0.

Writing code in Python to use HDWallet, but getting:
`TypeError: type 'HDS' is not subscriptable`
when going on this line:
```
hdwallet = HDWallet(cryptocurrency=BTC).from_mnemonic(k).from_derivation(derivation=CustomDerivation(path="m/44'/0'/"+str(i)+"'/0/"+str(j)))
```
Error is before first dot and after equal sign.
BTC is imported:
```
from hdwallet import HDWallet
from hdwallet.cryptocurrencies import Bitcoin as BTC
from hdwallet.derivations import CustomDerivation
```

**Comment by meherett** [comment]
Thank you for raising this issue, @pbies. The default HD set appears to have a problem. As a workaround, please set the HD config explicitly to resolve the issue.

```python
from hdwallet import HDWallet
from hdwallet.cryptocurrencies import Bitcoin as BTC
from hdwallet.derivations import CustomDerivation
from hdwallet.hds import BIP32HD  <-

hdwallet = HDWallet(cryptocurrency=BTC, hd=BIP32HD).from_mnemonic(k).from_derivation(derivation=CustomDerivation(path="m/44'/0'/"+str(i)+"'/0/"+str(j)))
```

**Comment by pbies** [comment]
Now I am getting:

`Traceback (most recent call last):
  File "/mnt/c/2/./mnemos2wifs-addrs-v4-deriv-paths.py", line 47, in <module>
    go(l)
  File "/mnt/c/2/./mnemos2wifs-addrs-v4-deriv-paths.py", line 30, in go
    hdwallet = HDWallet(cryptocurrency=BTC, hd=BIP32HD).from_mnemonic(k).from_derivation(derivation=CustomDerivation(path="m/44'/0'/"+str(i)+"'/0/"+str(j)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/hdwallet/hdwallet.py", line 340, in from_mnemonic
    if mnemonic.name() not in self._cryptocurrency.MNEMONICS.get_mnemonics():
       ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'`

**Comment by meherett** [comment]
The ``hdwallet.from_mnemonic`` function does not directly accept a string as its parameter. Instead, you need to provide a specific mnemonic class.

You should first import the desired mnemonic class using the following syntax:
```python
from hdwallet.mnemonics import <MnemonicClass>
```
Then, pass the imported class to the from_mnemonic function. This ensures proper handling and compatibility with the hdwallet library.

Eg:
```python
from hdwallet.mnemonics import BIP39Mnemonic
...
hdwallet = HDWallet(
    cryptocurrency=BTC
).from_mnemonic(
    mnemonic=BIP39Mnemonic(mnemonic=k or "...")
)
```

**Comment by pbies** [comment]
Thank you. All these info should be in documentation.

How to get addresses from wallet now? hdwallet.p2pkh_address() does not work.

**Comment by itsm3abena** [comment]
Try to pass using like this:-
```
print(hdwallet.address("P2PKH"))
```
Please check this [example](https://github.com/talonlab/python-hdwallet?tab=readme-ov-file#example)
and also [read the docs for further](https://hdwallet.readthedocs.io/en/master/hdwallet.html#hdwallet.HDWallet.address)

**Comment by pbies** [comment]
That works! Thank you!
