### ISSUE TITLE
Support Polygon "Mumbai" Testnet

### ISSUE THREAD

**Issue by JacobInCode** [talonlab/python-hdwallet#16]
Does the Polygon "Mumbai" testnet work with this HD Wallet implementation?

**Comment by blockskillally** [comment]
I'm I human .or am I just stress test not node.just going to get loo
ped spinning around and around I haven't acopleshed eny thing in 20 years I can't fish any thing before I have to do a factory reset

**Comment by meherett** [comment]
It's supported in the v3 package. Thank you.
