### ISSUE TITLE
generate DOGETEST address from XPUB

### ISSUE THREAD

**Issue by ikamran** [talonlab/python-hdwallet#53]
When I want to generate dogetest address from xpub i got this error messge:

```
site-packages\hdwallet\utils.py", line 343, in is_root_xpublic_key
    semantic.upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```
I used this example:
https://github.com/meherett/python-hdwallet/blob/master/examples/from_xpublic_key.py

**Comment by meherett** [comment]
Hi @ikamran, You are trying to generate dogetest address by the wrong xpub key. The DOGE and DOGETEST semantics are different from others. So, the XPublic key of DOGE is start from `dgub...` prefix and DOGETEST also `tpub...` prefix. Just make sure that.

For the error message, I will improve the message better way in the upcoming version.

Thanks.

**Comment by ikamran** [comment]
> Hi @ikamran, You are trying to generate dogetest address by the wrong xpub key. The DOGE and DOGETEST semantics are different from others. So, the XPublic key of DOGE is start from `dgub...` prefix and DOGETEST also `tpub...` prefix. Just make sure that.
> 
> For the error message, I will improve the message better way in the upcoming version.
> 
> Thanks.

for purpose of accepting transaction on my website is it true solution to use this hdwallet?
I mean the way binance and some shopping website using is the same?

**Comment by MarekSyk** [comment]
thank you it will come out  Marek

**Comment by meherett** [comment]
It's fixed the semantic issue in the v3 package. Thank you.
