### ISSUE TITLE
Multi currency support?

### ISSUE THREAD

**Issue by ccrvlh** [talonlab/python-hdwallet#76]
(I'm new to all this)

Looking at the docs and source, it seems this was built in a way that a user could only have a single passphrase/mnemonic for each currency/wallet, meaning that this does not have a so called "multi-coin" wallet support. By multi-coin what I mean is that the user would have a single recovery phrase, and that would generate different keys for different chains (using the different derivation schemes).

From the TrustWallet docs there's something like:

> Multi-Coin Wallet
The Multi-Coin Wallet is a structure allowing accounts for many coins, all controlled by a single recovery phrase. It is a standard HD Wallet (Hierarchically Derived), employing the standard derivation schemes, interoperable with many other wallets: BIP39 for recovery phrase, BIP44/BIP84 for account derivation.

Wondering if I'm interpreting things right, and whether there is a way to have multi currency support.
Thanks!

**Comment by meherett** [comment]
It's supported in the v3 package. Thank you.
