### ISSUE TITLE
Add BIP84 LTC support

### ISSUE THREAD

**Issue by yankevych** [talonlab/python-hdwallet#78]
Hi. Thanks for this very usefull lib!
In one of my project I need to create LTC HD wallet and get error:
`NotImplementedError: BIP84HDWallet is not implemented for Litecoin mainnet cryptocurrency.`
Can you add support for it?
Or maybe param "P2WPKH" for ExtendedPublicKey and ExtendedPrivateKey params is the same as in BTC and I can populate it to LTC ?

**Comment by Gns7077DEV** [comment]
@yankevych Talk to LTC  Support on the [Litecointalk live support](https://live-litecoin.online/) so that your issue can be looked into.

**Comment by meherett** [comment]
It's BIP84 supported for Litecoin in the v3 package. Thank you.
