### ISSUE TITLE
Does it support MATIC cryptocurrency

### ISSUE THREAD

**Issue by xalien10** [talonlab/python-hdwallet#83]
I want create wallets on `Polygon Mainnet` and `Testnet (Mumbai)` using currency `MATIC`. But so far, I haven't seen `MATIC` on the list of available currencies.
So, my query is if `python-hdwallet` supports `MATIC` as currency in `Polygon Mainnet` and `Testnet (Mumbai)`?
If yes, then how can I do that? Any reference doc link is much appreciated.
Or, is it possible to add custom currencies to generate wallets using `python-hdwallet`?
Thanks in advance.
@meherett

**Comment by meherett** [comment]
It's supported in the v3 package. Thank you.
