### ISSUE TITLE
BNB (Beacon Chain) address generation

### ISSUE THREAD

**Issue by hellsontime** [talonlab/python-hdwallet#91]
Trying to implement BNB BEP-2 support with no luck. The address should start from `bnb1`

Info i found already:
https://docs.bnbchain.org/docs/beaconchain/learn/accounts#cryptographic-design
https://bitcointalk.org/index.php?topic=5437885.0
https://bitcointalk.org/index.php?topic=5439078.0

It pretty straightforward to follow current implementation and just replace currency config with actual values, but just cannot get them, any ideas guys?

**Comment by meherett** [comment]
BNB supported in the v3 package. Thank you.
